server:
  port: 8080

spring:
  datasource:
    name: jwtdemo
    url: jdbc:mysql://rm-wz917pnes1070a8a2ro.mysql.rds.aliyuncs.com:3306/springbootdemo?useUnicode=true;characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lzj0437!
