mybatis:
  mapper-locations: classpath*:/com/lz/springbootjwt/mapper/xml/*.xml


spring:
  profiles:
    active: aliyun_datasource
    #active: dev


swagger:
  groupName: lalala
  basePackage: com.lz.springbootjwt
  title: 一只大肥橘
  version: 1.0
  desc: 一只大肥橘，向东流